# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        nats-version: ["2.7"]
        include:
          - python-version: "3.10"
            nats-version: "2.8"
          - python-version: "3.10"
            nats-version: "2.9"
          - python-version: "3.10"
            nats-version: "2.10"
          - python-version: "3.10"
            nats-version: "2.11"
          - python-version: "3.10"
            nats-version: "2.12"
    services:
      nats-server:
        image: nats:${{ matrix.nats-version }}
        ports:
          - 4222:4222

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: PDM setup
        uses: pdm-project/setup-pdm@v4
        with:
          # Version range or exact version of a Python version to use, using SemVer's version range syntax.
          python-version: ${{ matrix.python-version }}
          update-python: false
      - name: Install dependencies
        run: pdm install
      - name: Test with pytest
        env:
          NATS_SERVER_URL: nats://localhost:4222
        run: |
          pdm run test
